/* The schedule lives in one place so every event page stays up to date. */
const weddingEvents = [
  {
    id: "outbound-train",
    day: "27 Dec",
    date: "Sunday, 27 December 2026",
    time: "7:10 AM",
    title: "The journey begins",
    venue: "Secunderabad Jn Railway Station",
    category: "journey",
    summary: "We set off together for Bhopal on Train 22691.",
    details: ["Train number: 22691", "Boarding time: 7:10 AM", "Coach number: To be announced", "Seat numbers: To be announced"],
    map: "https://maps.app.goo.gl/dSaFnCo6ekKPRaWr9",
    mapLabel: "Open Secunderabad Jn map"
  },
  {
    id: "bhopal-arrival",
    day: "27 Dec",
    date: "Sunday, 27 December 2026",
    time: "8:55 PM",
    title: "Welcome to Bhopal",
    venue: "Bhopal Jn Railway Station",
    category: "journey",
    summary: "Train 22691 reaches Bhopal Jn at 8:55 PM. Rooms will be ready for check-in from 9:00 PM.",
    details: ["Arrival station: Bhopal Jn", "Arrival time: 8:55 PM", "Rooms check-in: from 9:00 PM", "Resort details: Fortune Resort & Gardens"],
    map: "https://maps.app.goo.gl/MjPHqGioGqBx4mKu5",
    mapLabel: "Open Bhopal Jn map"
  },
  {
    id: "check-in",
    day: "27 Dec",
    date: "Sunday, 27 December 2026",
    time: "9:00 PM onwards",
    title: "Rooms check-in",
    venue: "Fortune Resort & Gardens, Bhopal",
    category: "welcome",
    summary: "Settle in, freshen up, and get ready for three wonderful days together.",
    details: ["Fortune Resort & Gardens", "Bairagarh Kalan, Bairagarh, Bhopal – 462030, Madhya Pradesh", "Room allocation: To be announced", "Reception desk details: To be announced"],
    map: "https://maps.app.goo.gl/9rPVQdmpCpWCATGD6",
    mapLabel: "Open Fortune Resort & Gardens map"
  },
  {
    id: "breakfast-28",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "8:30 AM",
    title: "Breakfast",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "A relaxed breakfast before the festivities begin.",
    details: ["Dress code: To be announced", "Please arrive on time so the day can begin together."],
  },
  {
    id: "haldi-carnival",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "10:00 AM",
    title: "Haldi Carnival",
    venue: "Pool side",
    category: "haldi",
    summary: "Sunshine, laughter, and a joyful splash of haldi by the pool.",
    details: ["Event theme: To be announced", "Dress code: To be announced", "Additional instructions: To be announced"],
  },
  {
    id: "lunch-28",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "1:00 PM",
    title: "Lunch",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "A shared lunch between the daytime celebrations.",
    details: ["Dress code: To be announced", "Please arrive on time."],
  },
  {
    id: "mehendi",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "3:00 PM",
    title: "Mehendi Ceremony",
    venue: "Pool side",
    category: "mehendi",
    summary: "An afternoon of intricate henna, music, and warm conversations.",
    details: ["Event theme: To be announced", "Dress code: To be announced", "Additional instructions: To be announced"],
  },
  {
    id: "sangeet",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "7:00 PM",
    title: "Sangeet followed by Dinner",
    venue: "Banquet hall",
    category: "sangeet",
    summary: "An evening of music, dance, celebration, and dinner under glittering lights.",
    details: ["Dinner is included with the Sangeet function", "Event theme: To be announced", "Dress code: To be announced", "Additional instructions: To be announced"],
  },
  {
    id: "breakfast-29",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "8:30 AM",
    title: "Breakfast",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "Begin the second day of celebrations over breakfast.",
    details: ["Dress code: To be announced", "Please arrive on time."],
  },
  {
    id: "varapooja",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "10:30 AM",
    title: "Varapooja / Phal Daan",
    venue: "Banquet hall",
    category: "pooja",
    summary: "A meaningful ceremony bringing both families together.",
    details: ["Event theme: To be announced", "Dress code: To be announced", "Additional instructions: To be announced"],
  },
  {
    id: "lunch-29",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "1:00 PM",
    title: "Lunch",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "An afternoon lunch following the Varapooja / Phal Daan.",
    details: ["Dress code: To be announced", "Please arrive on time."],
  },
  {
    id: "baraat",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "5:00 PM",
    title: "Baraat Procession",
    venue: "Main entrance of the resort",
    category: "baraat",
    summary: "The celebrations arrive with rhythm, colour, and unmistakable joy.",
    details: ["Event theme: To be announced", "Dress code: To be announced", "Additional instructions: To be announced"],
  },
  {
    id: "reception",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "7:00 PM",
    title: "Reception followed by Dinner",
    venue: "Open sky lawn",
    category: "reception",
    summary: "An open-air evening to celebrate Rohit and Shreya, followed by dinner.",
    details: ["Dinner is included with the reception", "Event theme: To be announced", "Dress code: To be announced", "Additional instructions: To be announced"],
  },
  {
    id: "kashi-yatra",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "6:00 AM",
    title: "Kashi Yatra & Gauri Pooja",
    venue: "Marriage banquet hall",
    category: "pooja",
    summary: "The wedding day begins with cherished rituals and blessings.",
    details: ["Event theme: To be announced", "Dress code: To be announced", "Please arrive a few minutes early for the rituals."],
  },
  {
    id: "muhurtam",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "7:55 AM",
    title: "Jeelakara Bellam Muhurtam",
    venue: "Marriage banquet hall",
    category: "muhurtam",
    summary: "The auspicious moment when Rohit and Shreya begin their new chapter together.",
    details: ["Muhurtam: 7:55 AM IST", "Dress code: To be announced", "Please be seated before the ceremony begins."],
  },
  {
    id: "breakfast-30",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "8:30 AM",
    title: "Breakfast",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "Breakfast after the Jeelakara Bellam Muhurtam.",
    details: ["Dress code: To be announced", "Please arrive on time."],
  },
  {
    id: "homam",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "9:00 AM",
    title: "Homam & Lakshmi Pooja",
    venue: "Banquet hall",
    category: "pooja",
    summary: "A sacred morning of prayer, blessings, and togetherness.",
    details: ["Event theme: To be announced", "Dress code: To be announced", "Additional instructions: To be announced"],
  },
  {
    id: "lunch-30",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "1:00 PM",
    title: "Lunch",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "A final shared meal before check-out and the journey home.",
    details: ["Dress code: To be announced", "Please arrive on time."],
  },
  {
    id: "checkout",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "4:00 PM",
    title: "Rooms check-out",
    venue: "Wedding resort, Bhopal",
    category: "welcome",
    summary: "Please complete room check-out before the return journey.",
    details: ["Check-out time: 4:00 PM", "Luggage coordination: To be announced", "Resort details: To be announced"],
  },
  {
    id: "return-train",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "9:00 PM",
    title: "Journey home",
    venue: "Bhopal Jn Railway Station",
    category: "journey",
    summary: "We board Train 12589 for the journey back to Cherlapally.",
    details: ["Train number: 12589", "Departure time: 9:00 PM", "Coach number: To be announced", "Seat numbers: To be announced"],
    map: "https://maps.app.goo.gl/MjPHqGioGqBx4mKu5",
    mapLabel: "Open Bhopal Jn map"
  },
  {
    id: "cherlapally-arrival",
    day: "31 Dec",
    date: "Thursday, 31 December 2026",
    time: "1:30 PM",
    title: "Until we meet again",
    venue: "Cherlapally Railway Station",
    category: "journey",
    summary: "Train 12589 arrives at Cherlapally, bringing our shared journey to a close.",
    details: ["Arrival station: Cherlapally Railway Station", "Arrival time: 1:30 PM", "Thank you for being part of our celebrations."],
    map: "https://maps.app.goo.gl/GBfrULoSmMxC1pWL6",
    mapLabel: "Open Cherlapally station map"
  }
];

const eventThemes = {
  journey: { label: "Train journey", symbol: "🚆" },
  welcome: { label: "A warm welcome", symbol: "⌂" },
  dining: { label: "Food & fellowship", symbol: "🍽" },
  haldi: { label: "Sunlit celebration", symbol: "☀" },
  mehendi: { label: "Henna & harmony", symbol: "❋" },
  sangeet: { label: "Music & dance", symbol: "♫" },
  pooja: { label: "Sacred ritual", symbol: "◌" },
  baraat: { label: "Joy in motion", symbol: "✹" },
  reception: { label: "An evening together", symbol: "✧" },
  muhurtam: { label: "The auspicious hour", symbol: "❈" }
};
